
services:
  mysqldb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: grocerydb
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pdocker"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: hemvavarshiniramesh/grocery-backend:latest
    ports:
      - "2026:2026"
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    networks:
      - springboot-mysql-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2026/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  frontend:
    image: hemvavarshiniramesh/grocery-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: on-failure
    networks:
      - springboot-mysql-net

volumes:
  mysql-data:

networks:
  springboot-mysql-net:
    driver: bridge
