services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: grocery
      # MYSQL_USER: klu
      # MYSQL_PASSWORD: klu
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql   # volume added here

  backend:
    image: hemavarshiniramesh/grocery-backend:latest
    container_name: springboot
    ports:
      - "2025:2026"
    depends_on:
      - mysqldb
    restart: on-failure
    networks:
      - springboot-mysql-net

  frontend:
    image: hemavarshiniramesh/grocery-frontend:latest
    container_name: react
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: on-failure
    networks:
      - springboot-mysql-net

# Declare volumes at the bottom
volumes:
  mysql-data: