
services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: grocery
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3309:3306"
    networks:
      - springboot-mysql-net

  springboot:
    build:
      context: ./SPRINGBOOTWORKSPACE/GroceryStoreApplication  # Folder containing backend
      dockerfile: backend.Dockerfile
    container_name: springboot
    depends_on:
      - mysql-db
    ports:
      - "2028:2026"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/grocery?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: docker
    networks:
      - springboot-mysql-net

  react:
    build:
      context: ./client            # frontend root folder
      dockerfile: frontend.Dockerfile
    container_name: react
    ports:
      - "4000:80"
    depends_on:
      - springboot
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:

volumes:
  mysql-data:
