# docker-compose.yml
version: "3.9"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db-new
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: grocery
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-prootpassword"]
      interval: 10s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql

  springboot:
    build: ./GroceryStoreApplication
    container_name: springboot
    restart: always
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/grocery
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
    ports:
      - "2026:8080"  # Expose backend to host
    networks:
      - grocery-network

  react:
    build: ./frontend
    container_name: react
    restart: always
    environment:
      VITE_API_BASE_URL: http://springboot:8080/api
      VITE_CURRENCY: "₹"
    ports:
      - "5173:5173"  # Vite dev server
    depends_on:
      - springboot
    networks:
      - grocery-network

volumes:
  mysql-data:

networks:
  grocery-network:
    driver: bridge
