services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: grocery
      # MYSQL_USER: klu
      # MYSQL_PASSWORD: klu
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-net

  backend:
    image: hemavarshiniramesh/grocery-backend:latest
    container_name: springboot
    ports:
      - "2028:2028"
    depends_on:
      - mysqldb
    restart: on-failure
    networks:
      - springboot-mysql-net

  frontend:
    image: hemavarshiniramesh/grocery-frontend:latest
    container_name: react
    ports:
      - "4000:80"
    depends_on:
      - backend
    restart: on-failure
    networks:
      - springboot-mysql-net

# Declare volumes
volumes:
  mysql-data:

# ✅ Declare networks here
networks:
  springboot-mysql-net:
    driver: bridge
