
services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: grocery
    ports:
      - "3309:3306"
    networks:
      - springboot-mysql-net
    volumes:
      - mysql-data:/var/lib/mysql

  springboot:
    image: hemavarshiniramesh/grocery-backend:latest
    container_name: springboot
    depends_on:
      - mysql-db
    ports:
      - "2028:2026"
    networks:
      - springboot-mysql-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/grocery?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: docker

  react:
    image: hemavarshiniramesh/grocery-frontend:latest
    container_name: react
    ports:
      - "4000:80"
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:

volumes:
  mysql-data:
